name: Build and deploy to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

      - name: Deploy WebApp to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.USERNAME }}'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist/*'
          remote_path: '/srv/planting-calendar/www/'
          args: '-o ConnectTimeout=5'
